name: Deploy ACR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Login with federated identity (OIDC)
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 2: Fetch SP credentials JSON from Key Vault
      - name: Get SP credentials from Key Vault
        run: |
          CREDS=$(az keyvault secret show \
            --vault-name kv-wake-dev \
            --name sp-deployment-credentials \
            --query value -o tsv)
          echo "AZURE_CREDENTIALS=$CREDS" >> $GITHUB_ENV

      # Step 3: Login with SP JSON
      - name: Azure Login with SP JSON
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      # Step 4: Setup PowerShell
      - name: Setup PowerShell
        uses: PowerShell/PowerShell-Action@v1.2.3
        with:
          pwsh: '7.2.0'

      # Step 5: Run your deploy script
      - name: Deploy ACR
        run: pwsh ./status-tracker/ACR/deploy-acr.ps1 -Environment dev
